package com.amos_tech_code.knowledgebase.ui

// Data classes
data class KnowledgeItem(
    val id: Int,
    val title: String,
    val description: String,
    val category: String,
    val emoji: String
)

data class Quiz(
    val id: Int,
    val question: String,
    val options: List<String>,
    val correctAnswer: Int,
    val points: Int
)

// Dummy data providers
object DummyData {
    val knowledgeItems = listOf(
        KnowledgeItem(1, "Quantum Supremacy", "Quantum computers use 'qubits' which can exist in multiple states at once. In 2019, Google's Sycamore processor performed a calculation in 200 seconds that would take the world's fastest supercomputer 10,000 years!", "Technology", "💻"),
        KnowledgeItem(2, "The Deep Sea Frontier", "More than 80% of our ocean remains unmapped and unexplored. We actually have better maps of the surface of Mars and the Moon than we do of our own ocean floor!", "Nature", "🌊"),
        KnowledgeItem(3, "Neuralink & The Future", "Brain-computer interfaces (BCIs) are moving from sci-fi to reality. Companies like Neuralink aim to help paralyzed people control devices with their thoughts, and eventually, merge human intelligence with AI.", "Technology", "🧠"),
        KnowledgeItem(4, "The Library of Alexandria", "Once the center of the world's knowledge, this ancient library in Egypt held hundreds of thousands of scrolls. Its destruction remains one of the greatest losses of information in human history.", "History", "🏛️"),
        KnowledgeItem(5, "James Webb Space Telescope", "Orbiting 1.5 million kilometers from Earth, the JWST can see back in time to the very first galaxies formed after the Big Bang, using infrared light to peer through cosmic dust clouds.", "Space", "🔭"),
        KnowledgeItem(6, "The CRISPR Revolution", "CRISPR-Cas9 is a revolutionary gene-editing tool that acts like biological 'scissors'. It allows scientists to precisely edit DNA, offering potential cures for genetic diseases and even cancer.", "Science", "🧬"),
        KnowledgeItem(7, "The Great Green Wall", "An ambitious African-led movement to grow an 8,000km natural wonder of trees and plants across the entire width of Africa to combat climate change and desertification.", "Nature", "🌳"),
        KnowledgeItem(8, "The Antikythera Mechanism", "Discovered in a shipwreck, this 2,000-year-old Greek device is considered the world's first analog computer. It was used to predict astronomical positions and eclipses with incredible accuracy.", "History", "⚙️"),
        KnowledgeItem(9, "The Voyager Golden Record", "The Voyager 1 and 2 spacecraft each carry a gold-plated copper disk containing sounds and images selected to portray the diversity of life and culture on Earth to any extraterrestrial intelligence.", "Space", "📀"),
        KnowledgeItem(10, "M-Pesa: Financial Inclusion", "Launched in Kenya in 2007, M-Pesa revolutionized global finance by allowing millions of unbanked people to send and receive money via basic mobile phones. It is now a global case study for fintech.", "Technology", "📲"),
        KnowledgeItem(11, "The Mycelium Network", "Underground, fungi form massive networks called 'Wood Wide Webs'. They allow trees to communicate, share nutrients, and even warn each other about incoming pests or diseases.", "Nature", "🍄"),
        KnowledgeItem(12, "Large Hadron Collider", "The LHC is the world's largest and most powerful particle accelerator. In 2012, it confirmed the existence of the Higgs Boson, often called the 'God Particle', which gives mass to other particles.", "Science", "⚛️"),
        KnowledgeItem(13, "Renaissance Art Mastery", "Leonardo da Vinci's 'Mona Lisa' is famous for 'sfumato', a technique that creates soft, imperceptible transitions between colors and tones, making her expression appear to change depending on your focus.", "Arts", "🎨"),
        KnowledgeItem(14, "The International Space Station", "The ISS is a collaborative masterpiece involving 15 countries. It travels at 28,000 km/h, meaning astronauts on board witness 16 sunrises and sunsets every single day!", "Space", "🛰️"),
        KnowledgeItem(15, "Artificial Intelligence Ethics", "As AI systems like LLMs become more integrated into society, questions about bias, transparency, and 'alignment'—ensuring AI goals match human values—are becoming critical global challenges.", "Technology", "🤖"),
        KnowledgeItem(16, "The Rosetta Stone", "Discovered in 1799, this stone featured the same text in three scripts: Ancient Greek, Demotic, and Hieroglyphs. It was the key that finally allowed scholars to decipher Egyptian hieroglyphics.", "History", "📜"),
        KnowledgeItem(17, "Photosynthesis Efficiency", "Plants are masters of energy conversion. Scientists are trying to create 'artificial leaves' that mimic photosynthesis to produce clean hydrogen fuel directly from sunlight and water.", "Science", "🍃"),
        KnowledgeItem(18, "The Voyager Interstellar Mission", "Voyager 1 is the first human-made object to enter interstellar space. It is currently over 24 billion kilometers away from Earth and still sending back data from beyond our solar system.", "Space", "🚀"),
        KnowledgeItem(19, "Sustainable Architecture", "Modern 'Vertical Forests' are buildings covered in thousands of trees and shrubs. They absorb CO2, produce oxygen, and provide urban habitats for birds and insects while cooling the city.", "Nature", "🏢"),
        KnowledgeItem(20, "Blockchain Beyond Crypto", "While famous for Bitcoin, blockchain technology is being used for everything from tracking food supply chains to securing digital voting and managing medical records with immutable transparency.", "Technology", "⛓️"),
        KnowledgeItem(21, "The Great Barrier Reef", "The world's largest coral reef system is so big it can be seen from space. It is composed of over 2,900 individual reefs and is one of the most biodiverse ecosystems on the planet.", "Nature", "🐠"),
        KnowledgeItem(22, "Voynich Manuscript", "A 15th-century book written in an unknown script and language that has never been deciphered. Despite efforts by the world's top cryptographers, its meaning remains a total mystery.", "History", "📖"),
        KnowledgeItem(23, "Dark Matter & Energy", "Everything we can see—stars, planets, people—makes up only 5% of the universe. The rest is dark matter (27%) and dark energy (68%), mysterious substances we are still trying to understand.", "Space", "🌌"),
        KnowledgeItem(24, "Graphene: The Wonder Material", "Graphene is a single layer of carbon atoms arranged in a hexagonal lattice. It is 200 times stronger than steel, incredibly light, and the best known conductor of heat and electricity.", "Science", "⬢"),
        KnowledgeItem(25, "The Silk Road", "Not just one road, but a vast network of trade routes connecting East and West. It facilitated the exchange of goods, ideas, religions, and technologies for over 1,500 years.", "History", "🐫"),
        KnowledgeItem(26, "The Turing Test", "Proposed by Alan Turing in 1950, this test evaluates a machine's ability to exhibit intelligent behavior indistinguishable from that of a human. It remains a benchmark in AI philosophy.", "Technology", "📟"),
        KnowledgeItem(27, "Aurora Borealis", "Also known as the Northern Lights, this natural light display is caused by collisions between electrically charged particles from the sun that enter the earth's atmosphere.", "Nature", "✨"),
        KnowledgeItem(28, "The Fermi Paradox", "The contradiction between the high probability of extraterrestrial civilizations and the lack of evidence for, or contact with, such civilizations. 'Where is everybody?'", "Space", "👽"),
        KnowledgeItem(29, "Roman Concrete", "Ancient Romans used a volcanic ash-based concrete that was incredibly durable. Some Roman harbors still stand today, as the concrete actually gets stronger when exposed to seawater.", "History", "🧱"),
        KnowledgeItem(30, "Synthetic Biology", "A field that combines biology and engineering to design and construct new biological parts and systems. It could lead to custom-made organisms that produce medicine or fuel.", "Science", "🧫"),
        KnowledgeItem(31, "The Golden Ratio", "Represented by the Greek letter Phi (1.618), this mathematical ratio is found throughout nature and has been used by artists and architects for centuries to create aesthetic balance.", "Arts", "🐚"),
        KnowledgeItem(32, "Ocean Thermal Energy", "A technology that uses the temperature difference between cooler deep and warmer shallow ocean waters to run a heat engine and produce useful electricity.", "Nature", "🔋"),
        KnowledgeItem(33, "The Enigma Machine", "A cipher device used by Nazi Germany during WWII for military communication. Its code was famously broken by Alan Turing and his team at Bletchley Park, shortening the war.", "History", "🔐"),
        KnowledgeItem(34, "Exoplanets", "Planets that orbit stars outside our solar system. Since the first discovery in 1992, thousands have been found, some of which are in the 'habitable zone' where liquid water could exist.", "Space", "🪐"),
        KnowledgeItem(35, "CRISPR in Agriculture", "Beyond medicine, gene editing is being used to create crops that are resistant to drought, pests, and diseases, potentially securing the future of global food supplies.", "Science", "🌽"),
        KnowledgeItem(36, "Smart Grids", "Next-generation electrical grids that use digital communication technology to detect and react to local changes in usage, improving efficiency and integrating renewable energy.", "Technology", "⚡"),
        KnowledgeItem(37, "The Maya Calendar", "The Maya civilization developed highly sophisticated calendars, including the Long Count, which tracked time over thousands of years with incredible astronomical precision.", "History", "📅"),
        KnowledgeItem(38, "Bioluminescence", "The production and emission of light by a living organism, like fireflies or deep-sea fish. It's often used for communication, attracting prey, or defense.", "Nature", "🦑"),
        KnowledgeItem(39, "Gravitational Waves", "Ripples in the fabric of spacetime caused by some of the most violent and energetic processes in the universe, like the collision of black holes. Confirmed by LIGO in 2015.", "Space", "〰️"),
        KnowledgeItem(40, "3D Bioprinting", "An extension of 3D printing that uses 'bio-inks' to create structures that mimic natural tissues. The ultimate goal is to print entire functional organs for transplant.", "Technology", "🖨️"),
        KnowledgeItem(41, "The Bauhaus Movement", "A German art school operational from 1919 to 1933 that combined crafts and the fine arts. Its approach to design became one of the most influential currents in modern architecture.", "Arts", "📐"),
        KnowledgeItem(42, "Seed Vaults", "The Svalbard Global Seed Vault is a secure facility on a remote island that stores backups of the world's crop seeds to ensure food security in case of global disasters.", "Nature", "🌱"),
        KnowledgeItem(43, "The Industrial Revolution", "The transition to new manufacturing processes in Europe and the US in the 18th and 19th centuries, marking a major turning point in history and social structure.", "History", "🏭"),
        KnowledgeItem(44, "Hubble Deep Field", "An image of a small region in the constellation Ursa Major, constructed from a series of observations. It revealed thousands of galaxies in a tiny, seemingly empty patch of sky.", "Space", "🌌"),
        KnowledgeItem(45, "Solid State Batteries", "A battery technology that uses solid electrodes and a solid electrolyte, instead of liquid ones. They promise higher energy density and improved safety for electric vehicles.", "Technology", "🔌"),
        KnowledgeItem(46, "Cave Paintings", "Ancient artworks found on cave walls, some dating back over 40,000 years. They provide invaluable insights into the lives, beliefs, and artistic origins of early humans.", "Arts", "🦣"),
        KnowledgeItem(47, "Coral Bleaching", "A phenomenon where corals lose their vibrant colors due to stress from warming oceans. It's a critical indicator of climate change's impact on marine ecosystems.", "Nature", "🪸"),
        KnowledgeItem(48, "Particle-Wave Duality", "A fundamental concept of quantum mechanics that every particle or quantum entity may be described as either a particle or a wave. Light is the classic example.", "Science", "🌊"),
        KnowledgeItem(49, "The Wright Brothers", "Orville and Wilbur Wright are credited with inventing, building, and flying the world's first successful motor-operated airplane in 1903 at Kitty Hawk.", "History", "✈️"),
        KnowledgeItem(50, "Mars Rovers", "Robotic vehicles like Curiosity and Perseverance that explore the Martian surface. They search for signs of past life and prepare for future human exploration.", "Space", "🚜"),
        KnowledgeItem(51, "The Great Wall of China", "Stretching over 21,000 kilometers, this series of fortifications was built across the historical northern borders of ancient Chinese states to protect against nomadic groups.", "History", "🧱"),
        KnowledgeItem(52, "Theory of Relativity", "Albert Einstein's groundbreaking theory changed our understanding of space, time, and gravity, showing that they are intertwined in a four-dimensional fabric called spacetime.", "Science", "🎓"),
        KnowledgeItem(53, "Impressionism", "An 19th-century art movement characterized by small, thin, yet visible brush strokes and open composition, emphasizing the accurate depiction of light in its changing qualities.", "Arts", "🖌️"),
        KnowledgeItem(54, "The Hubble Space Telescope", "Launched in 1990, Hubble has provided some of the most detailed and awe-inspiring images of distant stars, nebulae, and galaxies, fundamentally changing astronomy.", "Space", "🌌"),
        KnowledgeItem(55, "Amazon Rainforest", "The world's largest tropical rainforest, often called the 'lungs of the planet' for its role in absorbing carbon dioxide and producing oxygen, while hosting unmatched biodiversity.", "Nature", "🐒"),
        KnowledgeItem(56, "Artificial Photosynthesis", "A chemical process that mimics the natural process of photosynthesis to convert sunlight, water, and carbon dioxide into carbohydrates and oxygen, or even fuels.", "Science", "🧪"),
        KnowledgeItem(57, "The Printing Press", "Johannes Gutenberg's 15th-century invention revolutionized the spread of information, sparking the Renaissance, the Reformation, and the Age of Enlightenment.", "History", "📜"),
        KnowledgeItem(58, "Magna Carta", "Issued in 1215, this royal charter of rights was the first document to publicly state that the king and his government were not above the law.", "History", "📜"),
        KnowledgeItem(59, "Renaissance Architecture", "Characterized by the use of classical elements like columns, domes, and arches, this style emphasized symmetry, proportion, and geometry in buildings like St. Peter's Basilica.", "Arts", "🏛️"),
        KnowledgeItem(60, "Black Holes", "Regions of spacetime where gravity is so strong that nothing, not even light, can escape. They are formed from the remnants of massive stars that have collapsed.", "Space", "🌑"),
        KnowledgeItem(61, "Renewable Energy", "Energy derived from natural sources that are replenished at a higher rate than they are consumed, such as sunlight, wind, and geothermal heat.", "Science", "♻️"),
        KnowledgeItem(62, "Internet of Things", "A network of physical objects embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices over the internet.", "Technology", "📡"),
        KnowledgeItem(63, "Roman Colosseum", "The largest ancient amphitheatre ever built, it was used for gladiatorial contests and public spectacles, representing the architectural and engineering peak of the Roman Empire.", "History", "🏟️"),
        KnowledgeItem(64, "Gothic Art", "A style of medieval art that developed in Northern France out of Romanesque art in the 12th century AD, led by the concurrent development of Gothic architecture.", "Arts", "⛪"),
        KnowledgeItem(65, "Mars Exploration", "The study of Mars through orbiting spacecraft and surface landers, aiming to understand the planet's history, climate, and potential for past or future life.", "Space", "☄️"),
        KnowledgeItem(66, "Biodiversity", "The variety and variability of life on Earth, encompassing all living organisms from genes to ecosystems, which is essential for maintaining a healthy and resilient planet.", "Nature", "🦋"),
        KnowledgeItem(67, "Quantum Entanglement", "A phenomenon where two or more particles become connected in such a way that the state of one particle instantly influences the state of the others, regardless of distance.", "Science", "⚛️"),
        KnowledgeItem(68, "Cloud Computing", "The on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user.", "Technology", "☁️"),
        KnowledgeItem(69, "Stonehenge", "A prehistoric monument in England consisting of a ring of standing stones, each around 13 feet high and weighing 25 tons. Its purpose and construction remain topics of debate.", "History", "🗿"),
        KnowledgeItem(70, "Cubism", "An early 20th-century avant-garde art movement that revolutionized European painting and sculpture by depicting subjects from multiple viewpoints simultaneously.", "Arts", "🔳"),
        KnowledgeItem(71, "Dark Matter", "A mysterious substance that makes up about 27% of the universe. It doesn't emit or reflect light, making it invisible, but its presence is known through its gravitational effects.", "Space", "🌌"),
        KnowledgeItem(72, "Climate Change", "The long-term shift in global temperatures and weather patterns, primarily driven by human activities like the burning of fossil fuels and deforestation.", "Nature", "🌡️"),
        KnowledgeItem(73, "Gene Therapy", "An experimental technique that uses genes to treat or prevent disease by inserting a gene into a patient's cells instead of using drugs or surgery.", "Science", "🏥"),
        KnowledgeItem(74, "Nanotechnology", "The manipulation of matter on an atomic, molecular, and supramolecular scale, with at least one dimension sized from 1 to 100 nanometers.", "Technology", "🔬"),
        KnowledgeItem(75, "Ancient Egypt", "A civilization in Northeast Africa that flourished along the Nile River, famous for its pyramids, hieroglyphs, pharaohs, and sophisticated religious beliefs.", "History", "⚱️"),
        KnowledgeItem(76, "Surrealism", "A 20th-century avant-garde movement in art and literature which sought to release the creative potential of the unconscious mind, often through irrational imagery.", "Arts", "🕰️"),
        KnowledgeItem(77, "Galaxies", "Massive systems of stars, stellar remnants, interstellar gas, dust, and dark matter, all bound together by gravity. Our own Milky Way is just one of billions.", "Space", "🔭"),
        KnowledgeItem(78, "Ecosystem Services", "The varied benefits that humans freely gain from the natural environment and from properly-functioning ecosystems, such as pollination and water purification.", "Nature", "🐝"),
        KnowledgeItem(79, "Nuclear Fusion", "The process by which two light atomic nuclei combine to form a single heavier one while releasing massive amounts of energy. It is the power source of stars.", "Science", "☀️"),
        KnowledgeItem(80, "Virtual Reality", "A simulated experience that can be similar to or completely different from the real world, typically achieved through headsets that provide immersive visual and auditory feedback.", "Technology", "🕶️"),
        KnowledgeItem(81, "The French Revolution", "A period of far-reaching social and political upheaval in France and its colonies beginning in 1789, which overthrew the monarchy and established a republic.", "History", "🚩"),
        KnowledgeItem(82, "Abstract Expressionism", "A post-World War II art movement in American painting, developed in New York City in the 1940s, characterized by spontaneous, gestural brushwork and emotional depth.", "Arts", "🎨"),
        KnowledgeItem(83, "The Big Bang", "The prevailing cosmological model for the observable universe from the earliest known periods through its subsequent large-scale evolution, starting around 13.8 billion years ago.", "Space", "💥"),
        KnowledgeItem(84, "Marine Biology", "The scientific study of marine life, organisms in the sea. It encompasses a vast range of organisms from microscopic plankton to massive whales.", "Nature", "🐠"),
        KnowledgeItem(85, "Superconductivity", "A physical property observed in certain materials where electrical resistance vanishes and magnetic flux fields are expelled from the material at very low temperatures.", "Science", "❄️"),
        KnowledgeItem(86, "Cybersecurity", "The practice of protecting systems, networks, and programs from digital attacks, which usually aim to access, change, or destroy sensitive information.", "Technology", "🔐"),
        KnowledgeItem(87, "The Renaissance", "A period in European history marking the transition from the Middle Ages to modernity and covering the 15th and 16th centuries, characterized by a revival of classical learning.", "History", "📜"),
        KnowledgeItem(88, "Baroque Art", "A style of architecture, music, dance, painting, sculpture, and other arts that flourished in Europe from the early 17th century until the 1740s.", "Arts", "🎻"),
        KnowledgeItem(89, "Galactic Evolution", "The study of the processes that formed a heterogeneous universe from a homogenous beginning, the formation of the first galaxies, and how galaxies change over time.", "Space", "🌀"),
        KnowledgeItem(90, "Endangered Species", "A species of animal or plant that is seriously at risk of extinction, often due to habitat loss, poaching, or environmental changes.", "Nature", "🐼"),
        KnowledgeItem(91, "Graphene", "A single layer of carbon atoms arranged in a hexagonal lattice, known for being incredibly strong, light, and an excellent conductor of heat and electricity.", "Science", "💎"),
        KnowledgeItem(92, "Artificial Intelligence", "The simulation of human intelligence processes by machines, especially computer systems, including learning, reasoning, and self-correction.", "Technology", "🤖"),
        KnowledgeItem(93, "The Viking Age", "The period during the Middle Ages when Norsemen known as Vikings undertook large-scale raiding, colonizing, conquest, and trading throughout Europe.", "History", "⛵"),
        KnowledgeItem(94, "Pop Art", "An art movement that emerged in the mid-1950s in Britain and the United States, challenging traditional fine art by including imagery from popular culture.", "Arts", "🥤"),
        KnowledgeItem(95, "Solar System Formation", "The process by which the Sun and its planets formed about 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud.", "Space", "☀️"),
        KnowledgeItem(96, "Atmospheric Science", "The study of the Earth's atmosphere and its various inner-working physical processes, including meteorology and climatology.", "Nature", "⛈️"),
        KnowledgeItem(97, "Synthetic Genomics", "A field of synthetic biology that uses aspects of genetic engineering to create new genetic material or entire organisms with specific functions.", "Science", "🧬"),
        KnowledgeItem(98, "5G Technology", "The fifth-generation technology standard for broadband cellular networks, offering significantly faster data speeds and lower latency than its predecessor, 4G.", "Technology", "📶"),
        KnowledgeItem(99, "World War II", "A global war that lasted from 1939 to 1945, involving the vast majority of the world's countries and forming two opposing military alliances: the Allies and the Axis.", "History", "🎖️"),
        KnowledgeItem(100, "Post-Modernism", "A broad movement that developed in the mid-to-late 20th century across philosophy, the arts, architecture, and criticism, marking a departure from modernism.", "Arts", "🖼️"),
        KnowledgeItem(101, "The Internet's Weight", "Did you know the entire internet weighs about as much as a strawberry? This is based on the mass of the electrons required to store all the information on the web.", "Technology", "🍓")
    )

    val quizzes = listOf(
        Quiz(1, "Which telescope is currently observing the earliest galaxies in the universe?", listOf("Hubble", "James Webb", "Kepler", "Spitzer"), 1, 30),
        Quiz(2, "How many sunrises do astronauts on the ISS see in 24 hours?", listOf("1", "4", "16", "24"), 2, 30),
        Quiz(3, "What percentage of the universe is composed of normal matter (things we can see)?", listOf("5%", "25%", "50%", "95%"), 0, 20),
        Quiz(4, "In which country was the mobile money system M-Pesa first launched?", listOf("Nigeria", "Kenya", "South Africa", "India"), 1, 25),
        Quiz(5, "What is the 'God Particle' more formally known as?", listOf("Photon", "Electron", "Higgs Boson", "Neutrino"), 2, 25),
        Quiz(6, "Which ancient mechanism is considered the world's first analog computer?", listOf("Rosetta Stone", "Antikythera Mechanism", "Voynich Manuscript", "Baghdad Battery"), 1, 30),
        Quiz(7, "What material is 200 times stronger than steel but only one atom thick?", listOf("Titanium", "Carbon Fiber", "Graphene", "Kevlar"), 2, 20),
        Quiz(8, "Which biological network allows trees to communicate and share nutrients?", listOf("Neural Network", "Mycelium Network", "Vascular System", "Root Matrix"), 1, 20),
        Quiz(9, "How much of the world's ocean remains unmapped and unexplored?", listOf("20%", "50%", "80%", "95%"), 2, 20),
        Quiz(10, "What script was deciphered using the Rosetta Stone?", listOf("Cuneiform", "Hieroglyphics", "Sanskrit", "Maya Glyphs"), 1, 25),
        Quiz(11, "Who proposed a test to see if a machine can think like a human?", listOf("Isaac Asimov", "Alan Turing", "John von Neumann", "Albert Einstein"), 1, 25),
        Quiz(12, "What causes the Aurora Borealis?", listOf("Moonlight", "Solar Particles", "City Lights", "Thunderstorms"), 1, 20),
        Quiz(13, "Which paradox asks 'Where is everybody?' regarding aliens?", listOf("Twin Paradox", "Fermi Paradox", "Grandfather Paradox", "Olbers' Paradox"), 1, 25),
        Quiz(14, "What did Romans add to their concrete to make it durable in seawater?", listOf("Sand", "Volcanic Ash", "Steel", "Sugar"), 1, 25),
        Quiz(15, "What is the approximate value of the Golden Ratio?", listOf("1.414", "1.618", "3.141", "2.718"), 1, 20),
        Quiz(16, "Where was the Enigma code famously broken during WWII?", listOf("The Pentagon", "Bletchley Park", "Peenemünde", "Los Alamos"), 1, 30),
        Quiz(17, "What is the name for planets orbiting stars outside our solar system?", listOf("Dwarf Planets", "Exoplanets", "Asteroids", "Quasars"), 1, 20),
        Quiz(18, "What is the process of light production by living organisms called?", listOf("Fluorescence", "Bioluminescence", "Photosynthesis", "Radiation"), 1, 20),
        Quiz(19, "Ripples in spacetime are known as what?", listOf("Radio Waves", "Gravitational Waves", "Microwaves", "Seismic Waves"), 1, 30),
        Quiz(20, "What technology aims to print human organs for transplants?", listOf("Laser Printing", "3D Bioprinting", "Etching", "Lithography"), 1, 30),
        Quiz(21, "What was the primary material used to build the Great Wall of China?", listOf("Wood", "Stone and Earth", "Iron", "Concrete"), 1, 25),
        Quiz(22, "Who developed the Theory of General Relativity?", listOf("Isaac Newton", "Albert Einstein", "Niels Bohr", "Stephen Hawking"), 1, 30),
        Quiz(23, "What is the main characteristic of Impressionist art?", listOf("Sharp details", "Depiction of light", "Solid black lines", "Abstract shapes"), 1, 25),
        Quiz(24, "When was the Hubble Space Telescope launched?", listOf("1970", "1980", "1990", "2000"), 2, 25),
        Quiz(25, "Which forest is known as the 'lungs of the planet'?", listOf("Taiga", "Congo Basin", "Amazon Rainforest", "Black Forest"), 2, 20),
        Quiz(26, "What does Blockchain technology provide for data?", listOf("Centralized control", "Immutable transparency", "Faster deletion", "Unlimited storage"), 1, 30),
        Quiz(27, "When was the Magna Carta issued?", listOf("1066", "1215", "1492", "1776"), 1, 25),
        Quiz(28, "What is the defining feature of a Black Hole?", listOf("Strong gravity", "High temperature", "Bright light", "Solid surface"), 0, 30),
        Quiz(29, "Which energy source is NOT renewable?", listOf("Solar", "Wind", "Natural Gas", "Geothermal"), 2, 20),
        Quiz(30, "What does 'IoT' stand for?", listOf("Internal of Things", "Internet of Things", "Input output Technology", "Integrated of Tools"), 1, 25),
        Quiz(31, "Where is the Roman Colosseum located?", listOf("Athens", "Rome", "Paris", "Istanbul"), 1, 20),
        Quiz(32, "Which art movement did Picasso co-found?", listOf("Impressionism", "Surrealism", "Cubism", "Pop Art"), 2, 25),
        Quiz(33, "What percentage of the universe is Dark Matter?", listOf("5%", "27%", "68%", "95%"), 1, 30),
        Quiz(34, "What is the primary driver of modern climate change?", listOf("Volcanic activity", "Solar flares", "Human activity", "Ocean currents"), 2, 25),
        Quiz(35, "What does VR stand for in technology?", listOf("Very Real", "Visual Reality", "Virtual Reality", "Vivid Response"), 2, 20),
        Quiz(36, "Which event started the French Revolution in 1789?", listOf("Storming the Bastille", "Execution of the King", "Battle of Waterloo", "Signing the Treaty"), 0, 30),
        Quiz(37, "In which decade did Abstract Expressionism develop?", listOf("1920s", "1940s", "1960s", "1980s"), 1, 25),
        Quiz(38, "How long ago did the Big Bang happen?", listOf("4.6 billion years", "13.8 billion years", "100 billion years", "1 million years"), 1, 30),
        Quiz(39, "What is the study of marine life called?", listOf("Geology", "Botany", "Marine Biology", "Astronomy"), 2, 20),
        Quiz(40, "What is the practice of protecting systems from digital attacks?", listOf("Data Mining", "Cybersecurity", "Programming", "Networking"), 1, 25),
        Quiz(41, "What period followed the Middle Ages in Europe?", listOf("The Industrial Age", "The Bronze Age", "The Renaissance", "The Iron Age"), 2, 25),
        Quiz(42, "Which country was the home of the Bauhaus movement?", listOf("Italy", "France", "Germany", "United Kingdom"), 2, 30),
        Quiz(43, "What material is 200 times stronger than steel?", listOf("Titanium", "Graphene", "Aluminum", "Carbon Fiber"), 1, 25),
        Quiz(44, "When did the Viking Age primarily occur?", listOf("100-300 AD", "500-700 AD", "800-1100 AD", "1300-1500 AD"), 2, 25),
        Quiz(45, "What does the 5 in 5G stand for?", listOf("5 times faster", "5 Gigahertz", "Fifth Generation", "5 Gigabit"), 2, 20),
        Quiz(46, "Who were the inventors of the first successful airplane?", listOf("The Wright Brothers", "Leonardo da Vinci", "The Montgolfier Brothers", "Charles Lindbergh"), 0, 25),
        Quiz(47, "Which planet is known as the Red Planet?", listOf("Venus", "Mars", "Jupiter", "Saturn"), 1, 20),
        Quiz(48, "What is the basic unit of life?", listOf("Atom", "Molecule", "Cell", "Organ"), 2, 20),
        Quiz(49, "Which ocean is the largest on Earth?", listOf("Atlantic", "Indian", "Arctic", "Pacific"), 3, 20),
        Quiz(50, "What is the tallest mountain in the world?", listOf("K2", "Mount Everest", "Kilimanjaro", "Denali"), 1, 20)
    )

    val funFacts = listOf(
        "A day on Venus is longer than a year on Venus! 🪐",
        "Honey never spoils. Archaeologists have found edible honey in 3,000-year-old Egyptian tombs. 🍯",
        "Bananas are technically berries, but strawberries are not! 🍌",
        "The heart of a shrimp is located in its head. 🦐",
        "A group of flamingos is called a 'flamboyance'. 🦩",
        "Wombat poop is cube-shaped to stop it from rolling away! 💩",
        "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion. 🗼",
        "Octopuses have three hearts and blue blood. 🐙",
        "There are more trees on Earth than stars in the Milky Way galaxy. 🌳",
        "A single bolt of lightning contains enough energy to toast 100,000 slices of bread. ⚡",
        "Bees can fly higher than Mount Everest! 🐝",
        "The first person convicted of speeding was going 8 mph in 1896. 🏎️",
        "Sharks have been around longer than trees! 🦈",
        "Your brain operates on about the same amount of power as a 20-watt light bulb. 💡",
        "Cows have 'best friends' and get stressed when they are separated. 🐄",
        "The smell of freshly cut grass is actually a plant distress call. 🌱",
        "A teaspoonful of a neutron star would weigh 6 billion tons! ⚛️",
        "There is a planet made of diamonds called 55 Cancri e. 💎",
        "An ostrich's eye is bigger than its brain. 👁️",
        "Rabbits can't vomit. 🐇",
        "A snail can sleep for three years! 🐌",
        "Scotland has 421 words for 'snow'. ❄️",
        "The fingerprints of koalas are so indistinguishable from humans' that they have on occasion been confused at crime scenes. 🐨",
        "The total weight of all the ants on Earth is roughly equal to the total weight of all the humans on Earth. 🐜",
        "Saturn's moon Titan has liquid methane lakes and you could fly there by flapping 'wings' attached to your arms. 🪐",
        "The word 'robot' comes from a Czech word meaning 'forced labor'. 🤖",
        "Polar bear skin is actually black, and their fur is translucent. 🐻‍❄️",
        "A cloud can weigh more than a million pounds. ☁️",
        "The moon has moonquakes just like Earth has earthquakes. 🌙",
        "The tongue of a blue whale is so large that 50 people could stand on it. 🐋",
        "Trees can recognize their offspring and will pass them nutrients. 🌳",
        "A small child could swim through the veins of a blue whale. 🐳",
        "There is enough DNA in your body to stretch from the Sun to Pluto and back — 17 times. 🧬",
        "The average person walks the equivalent of five times around the world in their lifetime. 🚶",
        "Venus is the only planet that rotates clockwise. 🪐",
        "Nutmeg is a hallucinogen if taken in large doses. 🌰",
        "The dot over the letter 'i' is called a tittle. ℹ️",
        "A jiffy is an actual unit of time: 1/100th of a second. ⏱️",
        "Horses and rats cannot vomit. 🐎",
        "The first oranges weren't orange — they were green. 🍊",
        "The inventor of the Frisbee was turned into a Frisbee after he died. 🛸",
        "There are no clocks in Las Vegas gambling casinos. 🎰",
        "A flamingo can eat only when its head is upside down. 🦩",
        "The majority of your brain is fat. 🧠",
        "It would take 1.2 million mosquitoes, each sucking once, to completely drain the average human of blood. 🦟",
        "The roar of a lion can be heard from 5 miles away. 🦁",
        "You can't hum while holding your nose. (Try it!) 👃",
        "The average person spends 6 months of their life waiting for red lights to turn green. 🚦",
        "Tigers have striped skin, not just striped fur. 🐯",
        "Koalas sleep for up to 22 hours a day. 🐨",
        "Sloths can take up to a month to completely digest a single leaf. 🦥",
        "Sea otters hold hands while they sleep to keep from drifting apart. 🦦",
        "The wood frog can stay frozen solid for up to seven months. 🐸",
        "Turritopsis dohrnii is a jellyfish that is biologically immortal. 🪼",
        "A narwhal's tusk is actually an enlarged tooth. 🦄",
        "The unique patterns of a giraffe's spots are like human fingerprints. 🦒",
        "Pigs are considered the fifth-most intelligent animal in the world. 🐷",
        "Squirrels plant thousands of new trees each year by forgetting where they buried their acorns. 🐿️",
        "A blue whale's heart is the size of a bumper car. 🐋",
        "Elephants are the only animals that can't jump. 🐘",
        "A group of owls is called a parliament. 🦉",
        "Hummingbirds are the only birds that can fly backwards. 🐦",
        "Crows can recognize human faces and hold grudges. 🐦‍⬛",
        "A snail can sleep for three years. 🐌",
        "Butterfly wings are actually transparent. 🦋",
        "Male seahorses are the ones who give birth to their young. 🐴",
        "Ants don't have lungs; they breathe through tiny holes all over their bodies. 🐜",
        "A cat has 32 muscles in each ear. 🐱",
        "The blue-ringed octopus is one of the world's most venomous animals. 🐙",
        "Kangaroos can't walk backwards. 🦘",
        "The Great Wall of China is not visible from space with the naked eye. 🧱",
        "A gold mining company in South Africa has the world's deepest mine, over 2.5 miles deep. ⛏️",
        "The world's smallest mammal is the bumblebee bat. 🦇",
        "The longest word in the English language has 189,819 letters. 📖",
        "There's a species of shark that can live for over 400 years. 🦈",
        "The human nose can detect over 1 trillion different scents. 👃",
        "The population of chickens on Earth is more than double the population of humans. 🐔",
        "A bolt of lightning is five times hotter than the surface of the sun. ⚡",
        "You share about 50% of your DNA with a banana. 🍌",
        "There's a volcano on Mars that is three times the height of Mount Everest. 🌋",
        "The total weight of all the ants on Earth is about the same as all the humans. 🐜",
        "The first computer mouse was made of wood. 🖱️",
        "The shortest war in history lasted only 38 minutes. ⚔️",
        "A single strand of spider silk is stronger than a steel wire of the same thickness. 🕸️",
        "The moon is moving away from the Earth at a rate of 1.5 inches per year. 🌙",
        "Your taste buds have a lifespan of about 10 to 14 days. 👅",
        "The heart of a blue whale is so large a human could swim through its arteries. 🐋",
        "There are more possible iterations of a game of chess than there are atoms in the observable universe. ♟️",
        "A day on Jupiter is only 10 hours long. 🪐",
        "The fingerprints of koalas are almost identical to human fingerprints. 🐨",
        "You can't burp in space because there's no gravity to separate liquid from gas in your stomach. 🚀",
        "The Eiffel Tower grows about 6 inches every summer. 🗼",
        "There are about 100 billion neurons in the human brain. 🧠",
        "The Pacific Ocean is larger than all the Earth's landmasses combined. 🌊",
        "An average person produces enough saliva in their lifetime to fill two swimming pools. 💧",
        "A newborn giant panda is about the size of a stick of butter. 🐼",
        "The Sahara Desert was once a lush green forest. 🏜️",
        "The smell of rain is caused by a bacteria called actinomycetes. 🌧️",
        "The shortest commercial flight in the world lasts only 57 seconds. ✈️",
        "There are no mosquitoes in Iceland. 🇮🇸"
    )
}
